version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-nw
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-nw
    environment:
      - MYSQL_ROOT_PASSWORD=S@tish3258
      - MYSQL_DATABASE=docker_db
    volumes:
      - /data/mysql
networks:
  springboot-db-nw: